export default {
  meta_title: 'Choengchai Phachonyut - Take a coffee and start work now!',
  meta_description: 'The world is changing!, No time for relax, take a coffee or beer and start work now!',
  home_page: 'Hello, World - Choengchai Phachonyut',
  about: 'home',
  resume: 'resume',
  project: 'project',
  skill: 'skills',
  blog: 'blogs',
  software: 'software',
  engineer: 'engineer',
  piaaop: 'Perfectionistic is an abstraction of professional',
  tgeitetmys_1: 'The good environment is the environment',
  tgeitetmys_2: 'that make you stronger',
  download_cv: 'download cv',
  experience: 'experience',
  present: 'present',
  tds_1: 'We make your e-commerce glowing !!',
  tds_2: 'We make an automated marketing !!',
  tds_3: 'Every actions of your client will send to you to let you know your target behavior and let you make the campaign or promotion that answer your client needed.',
  fnm_1: 'We working on decentralized identity platform',
  fnm_2: 'to bring greater trust and lower transaction.',
  fnm_3: 'We use blockchain technology to make our client data be privacy and we implement our core product to client core system to make it more immutable, verifiable, stable with lower cost.',
  education: 'education',
  acs: 'Assumption Sriracha',
  sci_math: 'SCI-MATH',
  mymf: 'Miss you my friend <3',
  ku_src: 'Kasetsart University SRC.',
  com_sci: 'Computer Sci.',
  ku_1: 'I’ve learned many thing from here.',
  ku_2: 'I’m very happy to have been there.',
  ku_3: 'Thank you Kasetsart sriracha ˙ᵕ˙',
  project_1: 'Developing ...',
  project_2: 'there are a lot of project that I made ',
  project_3: 'cannot wait to show it to you.',
  skill_1: 'Designing ...',
  skill_2: 'would you like to see my power?',
  skill_3: 'it wouldn\'t take long.',
  blog_1: 'Thinking ...',
  blog_2: 'there are a lot of knowledge',
  blog_3: 'cannot wait to share it to you :D',
  progressing: 'progressing',
  project_uploading: 'Adding project',
}
